apiVersion: v1
kind: Pod
metadata:
  name: ngnix-existing-vol
spec:
  containers:
  - name: server
    image: nginx:1.14
    volumeMounts:
      - mountPath: /var/lib/www/html
        name: quobytepvc
  volumes:
    - name: quobytepvc
      persistentVolumeClaim:
        claimName: quobyte-csi-test-pre