kind: PersistentVolume
apiVersion: v1
metadata:
  name: preprovisoned-quobyte-csi
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  # Delete Reclaim policy does not work with CSI for pre-provisioned volumes
  persistentVolumeReclaimPolicy: Retain
  storageClassName: quobyte-csi
  csi:
    driver: quobyte-csi
    # VolumeHandle should be of the format <API_URL>|<TENANT_NMAE/UUID>|<VOLUME_NAME/UUID>
    volumeHandle: http://api.quobyte:7860|My Tenant|test
    readOnly: false
    nodePublishSecretRef:
      name: quobyte-admin-secret
      namespace: quobyte
