name: Test helm chart
on: [push, pull_request]
jobs:
  container-job:
    runs-on: ubuntu-latest
    container:
      image: quintush/helm-unittest:3.3.0-0.2.2
    steps:
    - uses: actions/checkout@v1
    - run: -3 .
      working-directory: ./quobyte-csi-driver